order_eats/account/urls.py
from django.urls import path,include
from.import  views
from django.conf.urls import url
app_name='account'
urlpatterns = [
     path('',views.homepage,name='homepage'),
     path('signup/',views.signup,name='signup'),
     path('albertdream/',views.albertdream,name='albert'),
     url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
     url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
     path('resthome/',include('rest_details.urls',namespace='restinfo')),
     path('login/',views.login_view,name='login'),
     path('logout/',views.logout_view,name='logout'),
     #url(r'^cuisine/(?P<cuisine_type>[\w-]+)/$',views.cuisine_view,name='cuisine'),
     url(r'^resmain/(?P<slug>[\w-]+)/$',views.reserve_view,name='reserve'),
     #url(r'^(?P<cuisine_type>[\w-]+)/$',views.cuisine_view,name='cuisine'),
     path('cuisine/<cuisine_type>',views.cuisine_view,name='cui'),
     path('filter/',views.filter_view,name='filter'),
     path('casual-dining',views.casual_dining_view,name='casual_dining'),
     path('fine-dining',views.fine_dining_view,name='fine_dining'),
     path('bar',views.bar_view,name='bar'),
     path('cafe',views.cafe_view,name='cafe'),
     path('food-court',views.food_court_view,name='food_court'),
     path('bakeries',views.bakery_view,name='bakeries'),
     path('reservations/',include('reservations.urls',namespace='reservations')),
     path('previous/',views.previous,name='previous'),
     path('about-dhanush/',views.aboutdhanush,name='aboutdhanush'),
     #url(r'^(?P<slug>[\w-]+)/(?P<cuisine_type>[\w-]+)/$',views.cuisine_view,name='cuisine'),
     #url(r'^cuis/(?P<cuisine_type>[\w-]+)/cuis1/(?P<slug>[\w-]+)/$',views.res_view,name='res'),


    

    
   
]

order_eats/order_eats/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls',namespace='account')),
    path('resthome/',include('rest_details.urls',namespace='restinfo')),
    path('reservations/', include('reservations.urls',namespace='reservations')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

order_eats/reservations/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name='reservations'

urlpatterns = [

    path('status/',views.cust_tablereserve_view,name='cust_table_reserve_check'),
    url(r'^tablereserve/(?P<slug>[\w-]+)/$',views.index,name='index'),
    #path('',views.index,name='index'),
    url(r'^tablereservation/(?P<slug>[\w-]+)/$', views.addi,name='addi'),
    url(r'^edit-tablereservation/(?P<oid>[\w-]+)/$', views.customer_edit_reserve_view,name='cust_edit_reserve'),
    url(r'^appoint/$', views.appoint,name='appoint'),
    url(r'^order/(?P<slug1>[\w-]+)/(?P<slug2>[\w-]+)/$',views.order,name='menuorder'),
    url(r'^cart/(?P<itemid>[\w-]+)/(?P<slug>[\w-]+)/$',views.cart_view,name='cart'),
    url(r'^cart-delete/(?P<item_id>[\w-]+)/(?P<ord_slug>[\w-]+)/$',views.cartdelete_view,name='cartitem_delete'),
    url(r'^checkout/(?P<sl>[\w-]+)/$', views.checkout_view,name='checkout'),
    url(r'^payment/(?P<ordid>[\w-]+)/$', views.payment_view,name='payment'),
    url(r'^review//(?P<revordid>[\w-]+)/$', views.review_view,name='revordid'),
    url(r'^chat/(?P<chatordid>[\w-]+)/$', views.chat_view,name='chatordid'),
    
    #url(r'^cart/(?P<item>[\w-]+)/$',views.cart,name='cart'),
   
    #url(r'^update/(?P<appoint_id>\d+)$', views.update),
    #url(r'^logout$', views.logout),
    #url(r'^delete/(?P<appoint_id>\d+)$', views.delete),
    #url(r'^edit_appoint/(?P<appoint_id>\d+)$', views.edit_appoint),
]

order_eats/reservations/forms.py
from django import forms
from .models  import Appointment

class app(forms.ModelForm):
	class Meta:
		model=Appointment
		fields=['date','cust_email','contact_no','name','tablesize','mealchoice','slot']

order_eats/reservations/views.py
from django.shortcuts import render
from django.contrib import messages
from django.conf import settings
from django.core.mail import send_mail
from django.shortcuts import render, redirect,get_object_or_404
from django.db.models import Count
import datetime
from .models import Appointment 
from rest_details.models import restaurant_details,setting
from django.http import HttpResponseRedirect
from django.urls import reverse
from.forms import app
from datetime import date, datetime,time,timedelta
from menu.models import menu,cart,checkout,review,chat
import decimal
# Create your views here.
def index(request,slug):
	ob=slug
	form=app(request.POST)
	if form.is_valid():
		form.save()
	return render(request, 'reservations/ad.html',{'ob':ob,'form':form})


def appoint(request):
#    if 'id' not in request.session:
#        return redirect ("/")
	appointments= Appointment.objects.all()
	last_app = Appointment.objects.last()
	o=review.objects.filter(review_slug=last_app.tablename_slug)
	subject = 'Unique Reference Number for table Booking'
	message =last_app.order_id +" "+"is your unique Reference Number for booking reservation in restaurant"+" "+last_app.tablename_restaur
	to_email = last_app.cust_email
	from_email = settings.EMAIL_HOST_USER
	to_list = [to_email,settings.EMAIL_HOST_USER]
	send_mail( subject, message, from_email,to_list,fail_silently=True)


	#appointments= Appointment.objects.filter(order_id=Appointment.order_id)
	#user= Appointment.objects.get(id=request.session['id'])
#    user= User.objects.get(id=request.session['id'])
	# others = User.objects.all().exclude(appoint__id=request.session['id'])
	context = {
		#{}"user": user,
		'time': date.today(),
		"appointments": appointments,
		'last_app':last_app,
		'o':o
	}
	return render(request, 'reservations/success.html', context)

def addi(request,slug):
	if request.method != "POST":
		messages.error(request,"Can't add like that!")
		return redirect('reservations:index')
	else:
		ob=restaurant_details.objects.get(slug=slug)
		ob1=setting.objects.get(restaur_slug=slug)
		print(ob.Restaurant_name)


		add_appoint=Appointment.objects.appointval(request.POST,ob,ob1)

		for i in add_appoint:
			print(i)
		if add_appoint[0] == False:
			for each in add_appoint[1]:
				messages.error(request, each) #for each error in the list, make a message for each one.
			#return redirect(reverse('reservations:addi'))
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
		if add_appoint[0] == True:
			o=Appointment.objects.all()
			messages.success(request, 'Successfully Reserved')
			return redirect('reservations:appoint')

def cust_tablereserve_view(request):
	ob=Appointment.objects.all()
	q=request.POST.get("query")
	oid=q
	#ob1=restaurant_details.objects.all()
	for i in ob:
		if (((i.order_id==q) & (str(i.date) >= str(date.today()))) ) :
			rest_name=i.tablename_restaur

			rest=restaurant_details.objects.get(Restaurant_name=rest_name)
			obj=Appointment.objects.get(order_id=q)
			crt =cart.objects.filter(oid=q)
			check=checkout.objects.filter(ord_id=q)

			return render(request,'reservations/customer_tablereserve_check.html',{'obj':obj,'rest':rest,'crt':crt,'check':check,'oid':oid})
	messages.error(request,'Please enter your correct URF no (or) your appointment for URF no is in the past ')
	return redirect('account:homepage')


def cust_edit_reserve_view(request,oid):     
	instance=get_object_or_404(Appointment,order_id=oid)
	ob=Appointment.objects.get(order_id=oid)
	form=app(request.POST or None,instance=instance)
	if form.is_valid():
		error=[]
		instance=form.save(commit=False)
		date=form.cleaned_data['date']
		slot=form.cleaned_data['slot']
		restname=instance.tablename_restaur
		restslug=instance.tablename_slug
		ob1=setting.objects.get(restaur_slug=restslug)
		if(str(date)<str(date.today())):
			error.append('Please enter a future date')
		if len(Appointment.objects.filter(date = date ,slot=slot,tablename_restaur=restname)) >= ob1.no_of_reservations_per_hour:
			error.append("Oops!! Opted Time Slot is full, Please enter different Slot")
		if(str(slot)<str(datetime.now().strftime("%H:%M")) and str(date)<=str(date.today())):
			error.append('Please enter a future time slot')
		if len(error)>0:
			for each in error:
				messages.error(request,each)
			return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
		if(len(error)==0):
			instance.save()
			messages.success(request,'Congratulations.. your Resevation has been updated. Please Login again to verify')
			return redirect('account:homepage')
		#ob.date=form.cleaned_data['date']
		#print(form.cleaned_data['date'])
		#ob.cust_email=form.cleaned_data['cust_email']
		#ob.contact_no=form.cleaned_data['contact_no']
		#ob.task=form.cleaned_data['task']
		#ob.mealchoice=form.cleaned_data['mealchoice']
		#ob.tablesize=form.cleaned_data['tablesize']
		#slot=form.cleaned_data['slot']
		#ob.slot=slot
		#ob.save()
		#form.save()

		#messages.success(request,'Congratulations.. your Resevation has been updated. Please Login again to verify')
		#return redirect('account:homepage')
	context={
		  "instance":instance,
		  "form":form
	}
	return render(request,'reservations/cust_edit_reserve.html',context)



def customer_edit_reserve_view(request,oid):
	x=checkout.objects.filter(ord_id=oid).exists()
	oid=oid
	if not x:
		instance=get_object_or_404(Appointment,order_id=oid)
		ob=Appointment.objects.get(order_id=oid)
		form=app(request.POST or None,instance=instance)
		if form.is_valid():
			error=[]
			instance=form.save(commit=False)
			date=form.cleaned_data['date']
			slot=form.cleaned_data['slot']
			restname=instance.tablename_restaur
			restslug=instance.tablename_slug
			ob1=setting.objects.get(restaur_slug=restslug)
			if(str(date)<str(date.today())):
				error.append('Please enter a future date')
			if len(Appointment.objects.filter(date = date ,slot=slot,tablename_restaur=restname)) >= ob1.no_of_reservations_per_hour:
				error.append("Oops!! Opted Time Slot is full, Please enter different Slot")
			if(str(slot)<str(datetime.now().strftime("%H:%M")) and str(date)<=str(date.today())):
				error.append('Please enter a future time slot')
			if len(error)>0:
				for each in error:
					messages.error(request,each)
				return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
			if(len(error)==0):
				instance.save()
				messages.success(request,'Congratulations.. your Resevation has been updated. Please Login again to verify')
				return redirect('account:homepage')
		context={
		"instance":instance,
		"form":form
		}
		return render(request,'reservations/cust_edit_reserve.html',context)

	else:
		x=Appointment.objects.get(order_id=oid)
		rest=restaurant_details.objects.get(Restaurant_name=x.tablename_restaur,slug=x.tablename_slug)
		obj=Appointment.objects.get(order_id=oid)
		crt =cart.objects.filter(oid=oid)
		check=checkout.objects.get(ord_id=oid)
			
				
		messages.error(request,'Cannot Edit ,The food is already ordered')
		return render(request,'reservations/customer_tablereserve_check.html',{'oid':oid,'rest':rest,'obj':obj,'crt':crt,'check':check})


def order(request,slug1,slug2):
	obj=menu.objects.filter(rest_menu_slug=slug1,menu_type='veg_starter')
	obj1=menu.objects.filter(rest_menu_slug=slug1,menu_type='veg_maincourse')
	obj2=menu.objects.filter(rest_menu_slug=slug1,menu_type='nonveg_starter')
	obj3=menu.objects.filter(rest_menu_slug=slug1,menu_type='nonveg_maincourse')
	obj4=menu.objects.filter(rest_menu_slug=slug1,menu_type='Beverages')
	obj5=menu.objects.filter(rest_menu_slug=slug1,menu_type='vodka')
	obj6=menu.objects.filter(rest_menu_slug=slug1,menu_type='redwine')
	obj7=menu.objects.filter(rest_menu_slug=slug1,menu_type='veg_chinese')
	obj8=menu.objects.filter(rest_menu_slug=slug1,menu_type='nonveg_chinese')
	obj9=menu.objects.filter(rest_menu_slug=slug1,menu_type='wine')
	obj10=menu.objects.filter(rest_menu_slug=slug1,menu_type='beer')
	obj11=menu.objects.filter(rest_menu_slug=slug1,menu_type='pizza')
	obj12=menu.objects.filter(rest_menu_slug=slug1,menu_type='burger')
	obj13=menu.objects.filter(rest_menu_slug=slug1,menu_type='dessert')
	ob=cart.objects.filter(oid=slug2)
	ob1=Appointment.objects.get(order_id=slug2)
	slug=slug2
	error=[]
	newtime=ob1.slot
	presenttime=datetime.now().strftime("%H:%M")
	frmt="%H:%M"
	restime=datetime.strptime(newtime,frmt)-datetime.strptime(presenttime,frmt)

	if str(restime)>str(1) or str(date)>=str(date.today()):
		objet=menu.objects.filter(rest_menu_slug=slug1)
		return render(request,'reservations/order.html',{'obj':obj,'slug':slug,'ob':ob,'obj1':obj1,'obj2':obj2,'obj3':obj3,'obj4':obj4,'obj5':obj5})

   

	else:
		messages.error(request,'Your Resevation time is near, cannot order food,Time limit should be atleast Two hours ')
		messages.error(request,'Please edit your Reservation timings')
		return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
			
  

def cart_view(request,itemid,slug):
	obj=menu.objects.get(menu_id=itemid)
	o=cart.objects.filter(menu_id=itemid,oid=slug).exists()
	if request.GET.get('increase'):
		#var=request.GET.get('increase')
		obj1 = cart.objects.get(menu_id=itemid,oid=slug)
		obj1.quantity=obj1.quantity+1
		obj1.save()

	if request.GET.get('decrease'):
		#var=request.GET.get('increase')
		obj1 = cart.objects.get(menu_id=itemid,oid=slug)
		obj1.quantity=obj1.quantity-1
		if obj1.quantity==0:
			obj1.delete()
		else:
			obj1.save()

	if not o:
		cart.objects.create(oid=slug,menu_id=itemid,price=obj.price,rest_menu_slug=obj.rest_menu_slug,item_name=obj.item,item=obj)



	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
 

def checkout_view(request,sl):
	ob=cart.objects.filter(oid=sl)
	obj=Appointment.objects.get(order_id=sl)
	o=checkout.objects.filter(ord_id=sl).exists()
	pr=0
	for i in ob:
		pr=pr+(i.price*i.quantity)
	tax=decimal.Decimal(0.05)*pr
	tax=round(tax,2)
	total=pr+tax
	amount_to_be_paid=decimal.Decimal(0.2)*total
	amount_to_be_paid=round(amount_to_be_paid,2)
	if not o:

order_eats/reservations/templates/reservations/cust_edit_reserve.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

	<form method="POST" >
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit">Edit</button>
	</form>

	<div>
		{% if messages %}
                <ul class="messages">
                {% for message in messages %}
                <li style="color:red">{{ message }}</li>
                {% endfor %}
                </ul>
            {% endif %}
	</div>

</body>
</html>

order_eats/reservations/templates/reservations/customer_tablereserve_check.html
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
	<title></title>
</head>
<body style="margin-left: 75px; margin-right: 75px; ">
	<a href="{% url 'account:homepage' %}">back</a>
	<div class="contaner">
		 <h4>Here is your Appointment :</h4>
		 <hr>
		<table>
			<th>URF-No</th>
			<th>Customer Name</th>
			<th>Date of appointment</th>
			<th>Time of appointment</th>
			<th>No of persons</th>
			<th>Meal choice</th>
			<th>Restaurant</th>
			<th>Location</th>
			
			<tr>
				<td>{{obj.order_id}}</td>
				<td>{{obj.name}}</td>
				<td>{{obj.date}}</td>
				<td>{{obj.slot}}</td>
				<td>{{obj.tablesize}}</td>
				<td>{{obj.mealchoice}}</td>
				<td>{{obj.tablename_restaur}}</td>
				<td>{{rest.Area}}</td>

		    </tr>
		    
		</table>
		<a href="{% url 'reservations:cust_edit_reserve' oid=oid %}">Edit</a>
		<div>
		 {% if messages %}
                <ul class="messages">
                {% for message in messages %}
                <li style="color:red">{{ message }}</li>
                {% endfor %}
                </ul>
           {% endif %}
       </div>


	</div>

	<br>
	<br>
	<div>
		{% if crt %}
		<h3> Your Order:</h3>
		<hr style="margin-right:60%;">
	<table>
		
		{% for i in crt %}
		<tr>
			<td>{{i.item_name}}</td>
			<td>{{i.quantity}}</td>
			<td>{{i.price}}</td>
		</tr>
		{% endfor %}
		{% endif %}
	</table>
	{% if check %}
	<h4>Total Price:{{check.cart_price}}</h4>
	<h4>Total Tax:{{check.tax}}</h4>
	<br>
	<hr style="margin-right: 75%;">
    <span>
    	<h5 style="padding-right: 20px;">Total Payment:{{check.total}}</h5>
    	<h5 style="padding-right: 15px;">Amount Paid:{{check.amount_paid}}</h5>
    	<h5>Amount Due:{{check.amount_due}}</h5>
    </span>
    {% endif %}
	</div>
	<br>
	

	<div class="container">
        <h2>Chat</h2>
        <hr>
        <div class="container">
            <div class="container">
                <form method="POST" action="{% url 'reservations:chatordid' chatordid=obj.order_id  %}">
                    {% csrf_token %}
                <div class="form-group">
  <label for="usr">Name:</label>
  <input type="text" name="name" class="form-control" id="usr">
</div>
<div class="form-group">
  <label for="pwd">Message:</label>
  <input type="text" name='review' class="form-control" id="pwd">
</div>
 <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Add</i></button>
 </form>


                
            </div>
            
        </div>
        
    </div>


</body>
</html>

order_eats/reservations/templates/reservations/success.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <title></title>
    <style type="text/css">
        .con{
             position: relative;
             text-align: center;
             color: white;
             max-height: 50%;

             
        }
        
        .centered1{
            position: absolute;
            top: 30%;
            left: 25%;
        }

        .centered2{
            position: absolute;
            top:40%;
            left: 45%;
        }
    </style>
  </head>
  <body>
    <br>

    <div class="bg-image">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url 'account:homepage' %}">Order-Eat</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
   
    <form class="form-inline my-2 my-lg-0" method="GET" action="{% url 'account:filter' %}">
      <input class="form-control mr-sm-2" type="search"  name="q" placeholder="Search" value="{{request.GET.q}}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="glyphicon glyphicon-search"></i></button>
    </form>
  </div>
</nav>
</div>
<div class="con ">
        <img class="w3-opacity"  src="{% static 're2.jpg' %}"  style="width:100%; height: 50%" >
        <h1 class="centered1 " style="font-family: verdana; text-align: center">TASTE. TOUCH. HEAR. EXPERIENCE</h1>
        <img src="{% static 'order-eat.jpg' %}" style="width: 200px;" class="centered2">
        
        
    </div>





    <div class="container">
        <h4>SUCCESS!!</h4>
       
                <h2>Your Unique Reference Number</h2>
            
                    <h3>{{last_app.order_id}}</h3>

                    <hr style="background-color: red">

              
    </div>
    <div class="container">
      <div class="row">
        <div class="col">
             <button class="btn btn-primary"><a href="{% url 'reservations:menuorder' slug1=last_app.tablename_slug slug2=last_app.order_id %}" style="color: white;">Order Menu</a></button>
            
        </div>

        <div class="col">
             <button class="btn btn-primary"><a href="{% url 'reservations:cust_edit_reserve' oid=last_app.order_id %}" style="color: white;">Edit your reservation</a></button>
            
        </div>
          
      </div>
    </div>
    <br>
    <br>
    <br>
    <div class="container">
        <h2>Add reviews</h2>
        <hr>
        <div class="container">
            <div class="container">
                <form method="POST" action="{% url 'reservations:revordid' revordid=last_app.order_id  %}">
                    {% csrf_token %}
                <div class="form-group">
  <label for="usr">Name:</label>
  <input type="text" name="name" class="form-control" id="usr">
</div>
<div class="form-group">
  <label for="pwd">Review:</label>
  <input type="text" name='review' class="form-control" id="pwd">
</div>
 <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Add</i></button>
 </form>


                
            </div>
            
        </div>
        
    </div>


     <div class="container">
        <h2>People Reviews</h2>
        <hr>
        <div class="container">
            <div class="container">
                {% if o %}
                {% for i in o %}
                <h3>{{i.name}}</h3>
                <div class="container">
                    <h5>{{i.review}}</h5>
                    
                </div>
                {% endfor %}
                {% endif %}

                
            </div>
                
            
        </div>
        
    </div>


    <div class="container">
           {% if messages %}
                <ul class="messages">
                {% for message in messages %}
                <li style="color:red">{{ message }}</li>
                {% endfor %}
                </ul>
                <a href="{% url 'reservations:cust_edit_reserve' oid=last_app.order_id %}">Edit</a>
            {% endif %}

    </div>



  </body>
</html>