order_eats/account/urls.py
from django.urls import path,include
from.import  views
from django.conf.urls import url
app_name='account'
urlpatterns = [
     path('',views.homepage,name='homepage'),
     path('signup/',views.signup,name='signup'),
     path('albertdream/',views.albertdream,name='albert'),
     url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
     url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
     path('resthome/',include('rest_details.urls',namespace='restinfo')),
     path('login/',views.login_view,name='login'),
     path('logout/',views.logout_view,name='logout'),
     #url(r'^cuisine/(?P<cuisine_type>[\w-]+)/$',views.cuisine_view,name='cuisine'),
     url(r'^resmain/(?P<slug>[\w-]+)/$',views.reserve_view,name='reserve'),
     #url(r'^(?P<cuisine_type>[\w-]+)/$',views.cuisine_view,name='cuisine'),
     path('cuisine/<cuisine_type>',views.cuisine_view,name='cui'),
     path('filter/',views.filter_view,name='filter'),
     path('casual-dining',views.casual_dining_view,name='casual_dining'),
     path('fine-dining',views.fine_dining_view,name='fine_dining'),
     path('bar',views.bar_view,name='bar'),
     path('cafe',views.cafe_view,name='cafe'),
     path('food-court',views.food_court_view,name='food_court'),
     path('bakeries',views.bakery_view,name='bakeries'),
     path('reservations/',include('reservations.urls',namespace='reservations')),
     path('previous/',views.previous,name='previous'),
     path('about-dhanush/',views.aboutdhanush,name='aboutdhanush'),
     #url(r'^(?P<slug>[\w-]+)/(?P<cuisine_type>[\w-]+)/$',views.cuisine_view,name='cuisine'),
     #url(r'^cuis/(?P<cuisine_type>[\w-]+)/cuis1/(?P<slug>[\w-]+)/$',views.res_view,name='res'),


    

    
   
]

order_eats/order_eats/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls',namespace='account')),
    path('resthome/',include('rest_details.urls',namespace='restinfo')),
    path('reservations/', include('reservations.urls',namespace='reservations')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

order_eats/rest_details/urls.py
from django.urls import path,include
from .import views
from django.conf.urls import url
app_name='restinfo'
urlpatterns=[
     path('',views.resthomepage_view,name='resthomepage'),
     path('create/',views.restdetail_view,name='restdetail'),
     path('view/',views.restview_view,name='restviewdetail'),
     path('edit/',views.no_of_rest_update_view,name='no_of_restupdatdetail'),
     path('menu/',views.restmenu_view,name='restmenudetail'),
     url(r'^edit/(?P<slug>[\w-]+)/$',views.restupdate_view,name='restupdatedetail'),
     url(r'^tableview/(?P<slug>[\w-]+)/$',views.tablereserve_view,name='table_reserve_view'),
     url(r'^set/(?P<slug>[\w-]+)/$',views.no_of_setting_view,name='no_of_setting_view'),
     url(r'^settings/(?P<slug>[\w-]+)/$',views.reserve_settings_view,name='settings_view'),
     url(r'^setting/(?P<slug>[\w-]+)/$',views.reserve_setting_view,name='setting_view'),
     url(r'^menu-view/(?P<slg>[\w-]+)/$',views.menuview_view,name='menuviewdetail'),
     url(r'^menu-edit/(?P<itemid>[\w-]+)/$',views.menuedit_view,name='menuedit'),
     url(r'^menu-add/(?P<menuslug>[\w-]+)/$',views.menuadd_view,name='menuadd'),
     url(r'^menu-delete/(?P<itemid1>[\w-]+)/$',views.menudelete_view,name='menudelete'),


     


]

order_eats/menu/models.py
from django.db import models
from rest_details.models import restaurant_details
from reservations.models import Appointment
from rest_details.models import restaurant_details
from django.db.models.signals import post_save,pre_save
# Create your models here.

class menu(models.Model):
	veg_starter='Vegetarian Starter'
	nonveg_starter='Nonveg Starter'
	veg_maincourse='Vegetarian maincourse'
	nonveg_maincourse='Nonveg maincourse'
	dessert='Dessert'
	Beverages='Beverages'
	roti='roti'
	veg_chinese='veg_chinese'
	nonveg_chinese='nonveg_chinese'
	wine='wine'
	beer='beer'
	vodka='vodka'
	redwine='redwine'
	pizza='pizza'
	burger='burger'

	menutype=(
		('veg_starter','Vegetarian Starter'),
		('nonveg_starter','Nonveg Starter'),
		('veg_maincourse','Vegetarian maincourse'),
		('nonveg_maincourse','Nonveg maincourse'),
		('dessert','Dessert'),
		('Beverages','Beverages'),
		('roti','Rotis'),
		('veg_chinese','veg_chinese'),
		('nonveg_chinese','nonveg_chinese'),
		('wine','wine'),
		('beer','beer'),
		('vodka','vodka'),
		('redwine','redwine'),
		('pizza','pizza'),
		('burger','burger')
		)

	rest_menu=models.ForeignKey(restaurant_details,on_delete=models.SET_NULL,null=True,related_name='menurestaurant')
	menu_id=models.CharField(max_length=500,blank=True)
	rest_menu_slug=models.CharField(max_length=200,blank=True)
	item=models.CharField(max_length=200,blank=False)
	price=models.DecimalField(blank=False,max_digits=6,decimal_places=2)
	vegetarian_meal=models.BooleanField(blank=True)
	drinks=models.BooleanField(blank=True,default=False)
	menu_type=models.CharField(blank=False,max_length=50,choices=menutype,default='Vegetarian maincourse')

	def __str__(self):
		return self.menu_id


def pre_save_slug(instance,sender,*args,**kwargs):
	ob=restaurant_details.objects.get(Restaurant_name=instance.rest_menu)
	if not instance.rest_menu_slug:
		instance.rest_menu_slug=ob.slug
pre_save.connect(pre_save_slug,sender=menu)


def pre_save_menuid(instance,sender,*args,**kwargs):
	x=instance.rest_menu_slug
	y=instance.menu_id
	res=x+y
	ob=menu.objects.all()
	for i in ob:
		if i.menu_id==res:
			res=res+y
	instance.menu_id=res

pre_save.connect(pre_save_menuid,sender=menu)


class cart(models.Model):
	rest_cart=models.ForeignKey(restaurant_details,on_delete=models.SET_NULL,null=True,related_name='cartrestaurant')
	item_name=models.CharField(max_length=200,blank=True)
	oid=models.CharField(max_length=100,blank=False)
	menu_id=models.CharField(max_length=500,blank=True)
	rest_menu_slug=models.CharField(max_length=200,blank=True)
	item=models.ForeignKey(menu,on_delete=models.SET_NULL,null=True,related_name='cartmenu')
	price=models.DecimalField(blank=False,max_digits=6,decimal_places=2)
	quantity=models.PositiveIntegerField(default=1)

	def __str__(self):
		return self.oid

class checkout(models.Model):
	ord_id=models.CharField(max_length=100,blank=True)
	f_ord_id=models.ForeignKey(Appointment,on_delete=models.SET_NULL,null=True,related_name='checkoutrestaurant')
	cart_price=models.DecimalField(max_digits=10,decimal_places=4)
	tax=models.DecimalField(max_digits=4,decimal_places=2)
	total=models.DecimalField(max_digits=8,decimal_places=4)
	amount_paid=models.DecimalField(max_digits=8,decimal_places=4,default=0000.0000)
	amount_due=models.DecimalField(max_digits=8,decimal_places=4,default=0000.0000)
	payment=models.BooleanField(blank=False,default=False)

class review(models.Model):
	name=models.CharField(max_length=200,blank=False)
	review=models.TextField(blank=False)
	review_ordid=models.CharField(max_length=200,blank=True)
	review_slug=models.CharField(max_length=200,blank=True)

class chat(models.Model):
	name=models.CharField(max_length=200,blank=False)
	review=models.TextField(blank=False)
	review_ordid=models.CharField(max_length=200,blank=True)

order_eats/rest_details/forms.py
from django import forms
from .models  import restaurant_details,setting
from menu.models import menu

class Rest_Info(forms.ModelForm):
	class Meta:
		model=restaurant_details
		fields=['Restaurant_name','Area','City','zipcode','rest_choice','short_description','address','web_url','cuisine_type','profile_image','logo_image','location_image','Weekday_timings','Weekend_timings','cost_for_two_people','buffet','buffet_timing','alcohol_served','Cuisines_You_Offer','Type_of_dining','Restaurant_Special_Items']


class res_info(forms.ModelForm):
	class Meta:
		model=setting
		fields=['minimum_party_size','maximum_party_size','no_of_reservations_per_hour','breakfast_hours','lunch_hours','dinner_hours']

class menu_info(forms.ModelForm):
	class Meta:
		model=menu
		fields=['item','price','vegetarian_meal','menu_type']

class menu_infoadd(forms.ModelForm):
	class Meta:
		model=menu
		fields=['menu_id','item','price','vegetarian_meal','drinks','menu_type']

order_eats/menu/views.py
from django.shortcuts import render

# Create your views here.

order_eats/rest_details/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from . models import restaurant_details,setting
from reservations.models import Appointment
# Create your views here.
from django.contrib import messages
from .forms import Rest_Info,res_info
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from . import forms
from django.urls import reverse
from menu.models import menu 

@login_required(login_url="account:login")
def resthomepage_view(request):
	return render(request,'rest_details/resthomepage.html')

@login_required(login_url="account:login")	
def restdetail_view(request):
	if request.method=='POST':
		form=forms.Rest_Info(request.POST,request.FILES)
		if form.is_valid():
			instance=form.save(commit=False)
			instance.owner=request.user
			
			instance.save()
			slug=instance.slug
			messages.success(request,'Congratulations, you have created your Restaurant on Order-Eat')

			return render(request,'rest_details/res.html',{'slug':slug})
	else:
		form=forms.Rest_Info()
	return render(request,'rest_details/restdetail.html',{'form':form})

@login_required(login_url="account:login")	
def restview_view(request):
	ob=restaurant_details.objects.filter(owner=request.user)
	return render(request,'rest_details/restview.html',{'ob':ob})

@login_required(login_url="account:login")	
def tablereserve_view(request,slug):
	res=Appointment.objects.filter(tablename_slug=slug)
	appoint=restaurant_details.objects.get(slug=slug)
	return render(request,'rest_details/table_reserve.html',{'res':res,'appoint':appoint})

@login_required(login_url="account:login")	
def restupdate_view(request,slug):
	instance=get_object_or_404(restaurant_details,slug=slug)
	form=forms.Rest_Info(request.POST or None,request.FILES or None,instance=instance)
	if form.is_valid():
		instance=form.save(commit=False)
		instance.owner=request.user
		instance.save()
		messages.success(request,'Restaurant Details have beeen successfully updated')
		return redirect('restinfo:resthomepage')
	context={
	      "instance":instance,
	      "form":form
	}
	return render(request,'rest_details/rest_update.html',context)


def no_of_rest_update_view(request):
	ob=restaurant_details.objects.filter(owner=request.user)
	return render(request,'rest_details/no_of_rest_update.html',{'ob':ob})

def no_of_setting_view(request,slug):
	ob=restaurant_details.objects.get(slug=slug)
	if request.method=='POST':
		form=forms.res_info(request.POST)
		if form.is_valid():
			instance=form.save(commit=False)
			instance.restaur_name=ob
			instance.restaur_slug=ob.slug
			instance.save()
			#messages.success(request,'Congratulations, you have created your Restaurant on Order-Eat')
			return redirect('restinfo:no_of_restupdatdetail')
	else:
		form=forms.res_info()
	return render(request,'rest_details/reserve.html',{'form':form})

def reserve_settings_view(request,slug):
	instance=get_object_or_404(setting,restaur_slug=slug)
	ob=restaurant_details.objects.get(slug=slug)
	form=forms.res_info(request.POST or None,instance=instance)
	if form.is_valid():
		instance=form.save(commit=False)
		instance.restaur_name=ob
		instance.restaur_slug=ob.slug
		instance.save()
		return redirect('restinfo:resthomepage')
	else:
		context={
		"instance":instance,
		"form":form
		}
	return render(request,'rest_details/reservation_settings.html',context)

def reserve_setting_view(request,slug):
	ob=restaurant_details.objects.get(slug=slug)
	x=request.POST.get("minres")
	y=request.POST.get("maxres")
	z=request.POST.get("nores")
	setting.objects.create(minimum_party_size=x,maximum_party_size=y,no_of_reservations_per_hour=z,restaur_name=ob,restaur_slug=ob.slug)

	return redirect('restinfo:resthomepage')

@login_required(login_url="account:login")	
def restmenu_view(request):
	ob=restaurant_details.objects.filter(owner=request.user)
	return render(request,'rest_details/menuupdate.html',{'ob':ob})

def menuview_view(request,slg):
	o=menu.objects.filter(rest_menu_slug=slg)
	return render(request,'rest_details/menuview.html',{'o':o,'slg':slg})


def menuadd_view(request,menuslug):
	
	if request.method=='POST':
		obj=restaurant_details.objects.get(slug=menuslug)
		form=forms.menu_infoadd(request.POST)
		if form.is_valid():
			instance=form.save(commit=False)
			instance.rest_menu_slug=menuslug
			instance.rest_menu=obj
			instance.save()
			slg=menuslug
			messages.success(request,'Congratulations, you have added menu')

			return redirect('restinfo:resthomepage')
	else:
		form=forms.menu_infoadd()
	return render(request,'rest_details/menuadd.html',{'form':form})


def menuedit_view(request,itemid):
	instance=get_object_or_404(menu,menu_id=itemid)
	ob=menu.objects.get(menu_id=itemid)
	o=menu.objects.filter(rest_menu_slug=ob.rest_menu_slug)
	form=forms.menu_info(request.POST or None,instance=instance)
	if form.is_valid():
		instance=form.save(commit=False)
		instance.owner=request.user
		instance.save()
		messages.success(request,'Menu Details have beeen successfully updated')
		return redirect('restinfo:resthomepage')
	context={
	      "instance":instance,
	      "form":form,
	      "o":o,
	      "itemid":itemid,
	}

	return render(request,'rest_details/menuupdation.html',context)

def menudelete_view(request,itemid1):
	ob=menu.objects.get(menu_id=itemid1)
	ob.delete()
	return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

order_eats/rest_details/templates/rest_details/menuview.html
{% load static from staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <style type="text/css">
		#setting{
			display: block;
		}
	</style>

    <title>Home</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'dashboard.css'%}" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'account:homepage' %}">Order Eat</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="{% url 'account:logout' %}">Sign out</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'restinfo:restdetail' %}">
                  <span data-feather="home"></span>
                  Enter Restaurent Details <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'restinfo:restviewdetail' %}">
                  <span data-feather="file"></span>
                  Table Reservations
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'restinfo:no_of_restupdatdetail' %}">
                  <span data-feather="shopping-cart"></span>
                  Update Reservation Details
                </a>
              </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'restinfo:restmenudetail' %}">
                  
                  Menu
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'restinfo:resthomepage' %}">
                  <span data-feather="home"></span>
                  home
                </a>
              </li>
              
              
            </ul>

            
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            
          </div>
          <div>
          	<button class="btn btn-primary" style="margin-right:10px; "><a href="{% url 'restinfo:menuadd' menuslug=slg %}" style="color: white;">Add</a></button>
          	
          </div>
          <h3>Your Menu</h3>

          <div class="table-responsive">
		<table  class="table table-striped table-sm">
			<thead>
				<tr>
					<th>Menu-id</th>
		            <th>Item Name</th>
		<th>price</th>
		<th>Vegetarian</th>
		<th>Menu_type</th>
					
				</tr>
			</thead>
			<tbody>
				<tr>
			{% for i in o %}
			<td>
				{{i.menu_id}}
			</td>
			<td>{{i.item}}</td>
			<td>{{i.price}}</td>
			<td>{{i.vegetarian_meal}}</td>
			<td>{{i.menu_type}}</td>
			<td><button style="background-color: green;"><a href="{% url 'restinfo:menuedit' itemid=i.menu_id %}" style="color: white;">Edit</a></button></td>
			<td><button style="background-color: red;"><a href="{% url 'restinfo:menudelete' itemid1=i.menu_id %}" style="color: white">Delete</a></button></td>
			
		</tr>
		{% endfor %}
			</tbody>
			
		</table>
		
	</div>

         
	<script type="text/javascript">
		function myfunction(){
			document.getElementById("setting").display=none;
		}
	</script>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    
    <script src="{% static 'popper.min.js'%}"></script>
    <script src="{% static 'bootstrap.min.js'%}"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
  </body>
</html>

order_eats/rest_details/templates/rest_details/no_of_rest_update.html
{% load static from staticfiles %}

<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <style type="text/css">
		#setting{
			display: block;
		}
	</style>

    <title>Home</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap.min.css'%}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'dashboard.css'%}" rel="stylesheet">
  </head>

  <body>
    <nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'account:homepage' %}">Order Eat</a>
      <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
      <ul class="navbar-nav px-3">
        <li class="nav-item text-nowrap">
          <a class="nav-link" href="{% url 'account:logout' %}">Sign out</a>
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link active" href="{% url 'restinfo:restdetail' %}">
                  <span data-feather="home"></span>
                  Enter Restaurent Details <span class="sr-only">(current)</span>
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'restinfo:restviewdetail' %}">
                  <span data-feather="file"></span>
                  Table Reservations
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'restinfo:no_of_restupdatdetail' %}">
                  <span data-feather="shopping-cart"></span>
                  Update Reservation Details
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'restinfo:restmenudetail' %}">
                  
                  Menu
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'restinfo:resthomepage' %}">
                  <span data-feather="home"></span>
                  home
                </a>
              </li>
              
              
            </ul>

            
          </div>
        </nav>

        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            
          </div>

          <h2>Update Your Reservation Settings</h2>
          <hr>
         {% for i in ob %}
	<h3>
		<a href="{% url 'restinfo:restupdatedetail' slug=i.slug %}">Edit Details for {{i.Restaurant_name}}</a>
	</h3>
	
	<h3>
		<a href="{% url 'restinfo:settings_view' slug=i.slug %}" >Edit Reservation Settings for {{i.Restaurant_name}}</a>
	</h3>
	
	<br>
	<br>
	{% endfor %}
	<script type="text/javascript">
		function myfunction(){
			document.getElementById("setting").display=none;
		}
	</script>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    
    <script src="{% static 'popper.min.js'%}"></script>
    <script src="{% static 'bootstrap.min.js'%}"></script>

    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>

    <!-- Graphs -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
    <script>
      var ctx = document.getElementById("myChart");
      var myChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
          datasets: [{
            data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
            lineTension: 0,
            backgroundColor: 'transparent',
            borderColor: '#007bff',
            borderWidth: 4,
            pointBackgroundColor: '#007bff'
          }]
        },
        options: {
          scales: {
            yAxes: [{
              ticks: {
                beginAtZero: false
              }
            }]
          },
          legend: {
            display: false,
          }
        }
      });
    </script>
  </body>
</html>

order_eats/rest_details/templates/rest_details/res.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<form action="{% url 'restinfo:setting_view' slug=slug %}" method="POST">
		{% csrf_token %}
		<input type="text" name="minres">Min_res
		<input type="text" name="maxres">Max_res
		<input type="text" name="nores">no_of_reservations
		<button type="submit">save</button>
		
	</form>

</body>
</html>

order_eats/rest_details/templates/rest_details/reserve.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<form method="POST">
		{% csrf_token %}
		{{form.as_p}}
		<button type="submit">save</button>
	</form>

</body>
</html>